server:
  port: 9191

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Jairam@85
    url: jdbc:mysql://localhost:3306/masterdb
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
